version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: mongo
    ports:
    -  "27017:27017"
    volumes:
    -  mongo-data:/data/db
  flask-app:
    build: .
    container_name: flask-app
    ports:
    - "5000:5000"
    environment:
    - MONGO_URI=mongo://mongodb:27017/
    depends_on:
    - mongodb
    volumes:
    - .:/app
    command: python app.py

volumes:
  mongo-data:
